name: discord message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send custom message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#9146FF"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          message: "A new commit has been pushed on Heyimlulu/Paanya."

